language: erlang
notifications:
  email: false
otp_release:
  - R16B01
before_install:
   - "sh -e /etc/init.d/xvfb start && sudo aptitude -y -q install unzip chromium-browser"
   - git clone https://github.com/elixir-lang/elixir
   - make -C elixir
   - "export DISPLAY=:99.0"
   - "sh -e /etc/init.d/xvfb start"
   - mkdir -p "/tmp/bin"
   - "cd /tmp/bin && wget http://chromium.googlecode.com/files/chromedriver_linux32_16.0.902.0.zip && unzip chromedriver_linux32_16.0.902.0.zip"
before_script: "export PATH=`pwd`/elixir/bin:/tmp/bin:$PATH"
script: "MIX_ENV=test mix do deps.get, deps.compile, test"
